name: msbuild ci

on:
  push:
  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2

    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 5.3.1
    - run: nuget restore dotnetapp-dev.sln

    - uses: microsoft/setup-msbuild@v1.1
    - run: msbuild .\dotnetapp-dev.sln

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        queries: security-and-quality, security-extended
