name: msbuild ci

on:
  push:
  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

    - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: 5.3.1
      - run: nuget restore dotnetapp-dev.sln

